### ISSUE TITLE
Support searching npm directly

### ISSUE THREAD

**Issue by iamandrewluca** [kachkaev/njt#39]
Sometimes I want to search on npm.

- I can go to npmjs and search
- I can add npmjs as search engine and search directly in address bar

Would be great to have also this into njt, having `f` (find) as a keyword (`s` is already used)

```
njt -> google map react f -> https://www.npmjs.com/search?q=google+map+react
```

**Comment by kachkaev** [comment]
Hi @iamandrewluca! Thanks for the suggestion!

At the moment, `njt` splits the original input into words and derive the keyword from the second word. This means that `njt -> google map react f` would be the same as `njt → google m`. This is probably not what one would expect from the search.

Overall, I'm open to adding the search functionality. I guess we just need to think a bit more on how it would be spec'd. If search is present, it should not conflict with or change the existing flow.

**Comment by iamandrewluca** [comment]
@kachkaev added soem more changes to the PR, and tests also, can you please take a look?

**Comment by kachkaev** [comment]
I'm not sure about the approach in #40, to be honest. The diff itself is OK, but the feature ‘spec’ for which the code is written does not feel quite right to me. At the moment, the logic of the tool is straightforward and it is therefore easy for people to build a mental modal of what njt does. With `f` working not like any other keyword, users need more effort to make predictions on how things would work.

Perhaps, npm search is simply out of scope for njt? To me, it’s a search on its own, like google.

That said, I’m not fully against the feature in general. I just cannot see a clear spec that would allow it.

Happy to continue the discussion here. If adding npm search as a parallel search engine works for you too, happy to close the issue too.

**Comment by iamandrewluca** [comment]
I agree on this one too. using npm as a search engine should do the job. "npm jump to" not "npm search" :smile:
