### ISSUE TITLE
Support for Alfred?

### ISSUE THREAD

**Issue by mikestopcontinues** [kachkaev/njt#4]
I love this app! It would be great to make the same jumps from Alfred. Any thoughts about an official plugin?

**Comment by kachkaev** [comment]
Hi @mikestopcontinues, thanks for the idea! 🙌

I have not used Alfred for a few years, but found this in their docs: https://www.alfredapp.com/help/features/web-search/

Could you try configuring `njt` as a search engine there? You can follow [instructions in README for Chrome or Firefox](https://github.com/kachkaev/njt#-custom-search-engine-in-chrome). If it works, feel free to submit a PR with new instructions!
