### ISSUE TITLE
VSCode integration

### ISSUE THREAD

**Issue by axelboc** [kachkaev/njt#8]
Awesome project! I'm adding `njt` as a search bookmark in Firefox right away.

Another idea for a useful integration: a VSCode extension to add a single command to VSCode's command palette (accessible by pressing F1).

**Comment by kachkaev** [comment]
Hi Axel, I like your idea! Let’s see if we can make njt available via `LaunchX` – I just found this VSCode extension and created an issue: https://github.com/neibla/LaunchX/issues/42

**Comment by kachkaev** [comment]
Thanks again for your idea @axelboc! See https://github.com/kachkaev/njt/commit/94517ca8b99e5d9e607a417b172a28d98c807821 and let me know if you have any further thoughts 🙌

**Comment by axelboc** [comment]
It works like a charm, thanks!!
