### ISSUE TITLE
Suggest bundlephobia and unpkg entry

### ISSUE THREAD

**Issue by iamandrewluca** [kachkaev/njt#9]
I would like to suggest bundlephobia and unpkg entry.
I know that you can set a custom search engine, and query directly
Would be great to have them all aggregated in one tool.

```json
"njt react bundle": "https://bundlephobia.com/result?p=react",
"njt react unpkg": "https://unpkg.io/react"
```

https://bundlephobia.com/result?p=react
https://unpkg.io/react

**Comment by kachkaev** [comment]
Thanks for this issue @iamandrewluca!

Looks like there was unpkg already (`u`), just the description was wrong. I fixed that in https://github.com/kachkaev/njt/commit/6c868d09e0f7d477ef0d966bc6280cde258171ba and also added bundlephobia as `b`.

Enjoy and let me know if you spot any issues! 🙌

**Comment by iamandrewluca** [comment]
@kachkaev thanks a lot!
